ALTER PROC AD_CAPNHATTAIKHOAN
	@TAIKHOAN VARCHAR(20),
	@MATKHAU VARCHAR(20)
AS
BEGIN TRAN
SET TRAN ISOLATION LEVEL SERIALIZABLE
		IF NOT EXISTS(SELECT * FROM TAIKHOAN TK WITH(UPDLOCK) WHERE TK.TAIKHOAN = @TAIKHOAN)
		BEGIN
			PRINT @TAIKHOAN + N' KHÔNG TỒN TẠI'
			ROLLBACK TRAN
			RETURN 0
		END
		IF EXISTS(SELECT * FROM TAIKHOAN TK WITH(UPDLOCK) WHERE TK.TAIKHOAN = @TAIKHOAN AND TK.KICHHOAT = 0)
		BEGIN
			PRINT @TAIKHOAN + N' ĐÃ BỊ KHÓA'
			ROLLBACK TRAN
			RETURN 0
		END
		WAITFOR DELAY '0:00:10'
		UPDATE TAIKHOAN
		SET MATKHAU = @MATKHAU
		WHERE TAIKHOAN = @TAIKHOAN
COMMIT TRAN
RETURN 1
GO

ALTER PROC DT_CAPNHATTAIKHOAN
	@MADT CHAR(5),
	@MATKHAU VARCHAR(20)
AS
BEGIN TRAN
SET TRAN ISOLATION LEVEL READ COMMITTED
		DECLARE @TAIKHOAN VARCHAR(20)
		SET @TAIKHOAN = (SELECT TK.TAIKHOAN FROM TAIKHOAN TK WITH(UPDLOCK) WHERE TK.MANGUOIDUNG = @MADT AND TK.VAITRO = 'client')
		IF NOT EXISTS(SELECT * FROM TAIKHOAN TK WITH(UPDLOCK) WHERE TK.TAIKHOAN = @TAIKHOAN)
		BEGIN
			PRINT @MADT + N' TÀI KHOẢN KHÔNG TỒN TẠI'
			ROLLBACK TRAN
			RETURN 0
		END
		IF EXISTS(SELECT * FROM TAIKHOAN TK WITH(UPDLOCK) WHERE TK.TAIKHOAN = @TAIKHOAN AND TK.KICHHOAT = 0)
		BEGIN
			PRINT @MADT + N' TÀI KHOẢN ĐÃ BỊ KHÓA'
			ROLLBACK TRAN
			RETURN 0
		END
		WAITFOR DELAY '0:00:10'
		UPDATE TAIKHOAN
		SET MATKHAU = @MATKHAU
		WHERE TAIKHOAN = @TAIKHOAN
COMMIT TRAN
RETURN 1