CREATE
--ALTER
PROC DT_THEMSANPHAM 
	@MASP CHAR(5),
	@TENSP NVARCHAR(50),
	@GIA FLOAT(5),
	@DOITAC CHAR(5),
	@CHINHANH NVARCHAR(50)
AS
BEGIN TRAN
	BEGIN TRY
		IF NOT EXISTS(SELECT * FROM DOITAC DT WHERE DT.MADT=@DOITAC)
		BEGIN
			PRINT @DOITAC + N' KHÔNG TỒN TẠI'
			ROLLBACK TRAN
			RETURN 0
		END
		IF NOT EXISTS(SELECT * FROM DOITAC DT WHERE DT.MADT=@DOITAC)
		BEGIN
			PRINT @DOITAC + N' KHÔNG TỒN TẠI'
			ROLLBACK TRAN
			RETURN 0
		END
		IF NOT EXISTS(SELECT * FROM CHINHANH CN WHERE CN.MADT=@DOITAC AND CN.DCHI=@CHINHANH)
		BEGIN
			PRINT @CHINHANH + N' KHÔNG TỒN TẠI'
			ROLLBACK TRAN
			RETURN 0
		END
		INSERT INTO SANPHAM VALUES (@MASP, @TENSP, @GIA, @DOITAC, @CHINHANH)
		WAITFOR DELAY '0:00:10'
		IF @TENSP IS NULL OR @GIA <= 0
		BEGIN
			ROLLBACK TRAN
			RETURN 0
		END
	END TRY
	BEGIN CATCH
		PRINT N'LỖI HỆ THỐNG'
		ROLLBACK TRAN
		RETURN 0
	END CATCH
COMMIT TRAN
RETURN 1
GO

CREATE
--ALTER 
PROC KH_XEMSANPHAM
	@MADT CHAR(5)
AS 
BEGIN TRAN
SET TRAN ISOLATION LEVEL READ UNCOMMITTED
		IF NOT EXISTS(SELECT * FROM DOITAC DT WHERE DT.MADT=@MADT)
		BEGIN
			PRINT @MADT + N' KHÔNG TỒN TẠI'
			ROLLBACK TRAN
			RETURN 0
		END
		SELECT SP.MASP, SP.TENSP, SP.GIA, SP.CHINHANH
		FROM SANPHAM SP
		WHERE SP.MADT = @MADT
COMMIT TRAN
RETURN 1