CREATE
--ALTER
PROC KH_HUYDONHANG
	@MAKH CHAR(5),
	@MADH CHAR(5)
AS
BEGIN TRAN
	BEGIN TRY
		IF NOT EXISTS(SELECT * FROM DONHANG DH WHERE DH.MADH=@MADH)
		BEGIN
			PRINT @MADH + N' KHÔNG TỒN TẠI'
			ROLLBACK TRAN
			RETURN 0
		END
		IF NOT EXISTS(SELECT * FROM DONHANG DH WHERE DH.MADH=@MADH AND DH.KHACHHANG=@MAKH)
		BEGIN
			PRINT @MADH + N' KHÔNG THUỘC VỀ ' + @MAKH
			ROLLBACK TRAN
			RETURN 0
		END
		DECLARE @SL INT
		SET @SL = (SELECT DT.SLDON FROM DONHANG DH JOIN SANPHAM SP ON DH.SANPHAM = SP.MASP JOIN DOITAC DT ON SP.MADT = DT.MADT WHERE DH.MADH = @MADH)
		UPDATE DOITAC
		SET SLDON = @SL - 1
		WHERE MADT = (SELECT SP.MADT FROM DONHANG DH JOIN SANPHAM SP ON DH.SANPHAM = SP.MASP WHERE DH.MADH=@MADH)
		DELETE DONHANG
		WHERE MADH = @MADH
	END TRY
	BEGIN CATCH
		PRINT N'LỖI HỆ THỐNG'
		ROLLBACK TRAN
		RETURN 0
	END CATCH
COMMIT TRAN
RETURN 1
GO

CREATE
--ALTER 
PROC DT_CAPNHATDONHANG
	@MADT CHAR(5),
	@MADH CHAR(5),
	@TINHTRANG NVARCHAR(30)
AS
BEGIN TRAN
	BEGIN TRY
		IF NOT EXISTS(SELECT * FROM DONHANG DH WHERE DH.MADH=@MADH)
		BEGIN
			PRINT @MADH + N' KHÔNG TỒN TẠI'
			ROLLBACK TRAN
			RETURN 0
		END
		IF @MADT <> (SELECT SP.MADT FROM DONHANG DH JOIN SANPHAM SP ON DH.SANPHAM = SP.MASP WHERE DH.MADH=@MADH)
		BEGIN
			PRINT @MADH + N' KHÔNG THUỘC VỀ ' + @MADT
			ROLLBACK TRAN
			RETURN 0
		END
		IF @TINHTRANG NOT IN(N'ĐÃ HỦY', N'ĐANG VẬN CHUYỂN')
		BEGIN
			PRINT @TINHTRANG + N' KHÔNG HỢP LỆ'
			ROLLBACK TRAN
			RETURN 0
		END
		IF @TINHTRANG = N'ĐÃ HỦY'
		BEGIN
			DECLARE @SL INT
			SET @SL = (SELECT DT.SLDON FROM DOITAC DT WITH(TABLOCKX) WHERE DT.MADT = @MADT)
			WAITFOR DELAY '0:00:10'
			UPDATE DOITAC
			SET SLDON = @SL - 1
			WHERE MADT = (SELECT SP.MADT FROM DONHANG DH JOIN SANPHAM SP ON DH.SANPHAM = SP.MASP WHERE DH.MADH=@MADH)
			DELETE DONHANG
			WHERE MADH = @MADH
		END
		ELSE
		BEGIN
			UPDATE DONHANG
			SET TINHTRANG = @TINHTRANG
			WHERE MADH = @MADH
		END
	END TRY
	BEGIN CATCH
		PRINT N'LỖI HỆ THỐNG'
		ROLLBACK TRAN
		RETURN 0
	END CATCH
COMMIT TRAN
RETURN 1
GO