CREATE 
--ALTER
PROC KH_HUYDONHANG
	@MAKH CHAR(5),
	@MADH CHAR(5)
AS
BEGIN TRAN
	BEGIN TRY
		IF NOT EXISTS(SELECT * FROM DONHANG DH WHERE DH.MADH=@MADH)
		BEGIN
			PRINT @MADH + N' KHÔNG TỒN TẠI'
			ROLLBACK TRAN
			RETURN 0
		END
		IF NOT EXISTS(SELECT * FROM DONHANG DH WHERE DH.MADH=@MADH AND DH.KHACHHANG=@MAKH)
		BEGIN
			PRINT @MADH + N' KHÔNG THUỘC VỀ ' + @MAKH
			ROLLBACK TRAN
			RETURN 0
		END
		UPDATE DOITAC
		SET SLDON = SLDON - 1
		WHERE MADT = (SELECT SP.MADT FROM DONHANG DH JOIN SANPHAM SP ON DH.SANPHAM = SP.MASP WHERE DH.MADH=@MADH)
		DELETE DONHANG
		WHERE MADH = @MADH
	END TRY
	BEGIN CATCH
		PRINT N'LỖI HỆ THỐNG'
		ROLLBACK TRAN
		RETURN 0
	END CATCH
COMMIT TRAN
RETURN 1
GO

CREATE 
--ALTER
PROC TX_NHANDONHANG
	@MATX CHAR(5),
	@MADH CHAR(5)
AS
BEGIN TRAN
	BEGIN TRY
		IF NOT EXISTS(SELECT * FROM DONHANG DH WHERE DH.MADH=@MADH)
		BEGIN
			PRINT @MADH + N' KHÔNG TỒN TẠI'
			ROLLBACK TRAN
			RETURN 0
		END
		IF EXISTS(SELECT * FROM DONHANG DH WHERE DH.MADH=@MADH AND DH.NGUOIGIAO IS NOT NULL)
		BEGIN
			PRINT @MADH + N' ĐÃ CÓ NGƯỜI NHẬN'
			ROLLBACK TRAN
			RETURN 0
		END
		WAITFOR DELAY '0:0:10'
		DECLARE @COUNT INT
		UPDATE DONHANG
		SET NGUOIGIAO = @MATX
		WHERE MADH = @MADH
		SET @COUNT = @@ROWCOUNT
		IF(@COUNT = 0)
		BEGIN
			ROLLBACK TRAN
			RETURN 0
		END
	END TRY
	BEGIN CATCH
		PRINT N'LỖI HỆ THỐNG'
		ROLLBACK TRAN
		RETURN 0
	END CATCH
COMMIT TRAN
RETURN 1
GO