CREATE DATABASE DB_QUANLYDATHANG
GO
USE DB_QUANLYDATHANG
CREATE TABLE DOITAC(
	MADT CHAR(5),
	TEN NVARCHAR(50),
	NGDAIDIEN NVARCHAR(50),
	THANHPHO NVARCHAR(50),
	QUAN NVARCHAR(50),
	SOCN INT CHECK (SOCN>=0),
	SLDON INT CHECK (SLDON>=0),
	LOAIHANG NVARCHAR(50),
	DCHI NVARCHAR(50),
	SODT VARCHAR(20),
	EMAIL VARCHAR(20),
	PRIMARY KEY(MADT)
)
CREATE TABLE CHINHANH(
	MADT CHAR(5),
	DCHI NVARCHAR(50),
	PRIMARY KEY(MADT, DCHI)
)
CREATE TABLE HOPDONG(
	MAHD CHAR(5),
	MATHUE CHAR(10),
	NGDAIDIEN NVARCHAR(50),
	SOCNDKY INT CHECK (SOCNDKY>=0),
	HIEULUC DATETIME,
	PRIMARY KEY(MAHD)
)
CREATE TABLE CHINHANHDKY(
	MAHD CHAR(5),
	MADT CHAR(5), 
	DCHI NVARCHAR(50),
	PRIMARY KEY(MAHD, MADT, DCHI)
)
CREATE TABLE SANPHAM(
	MASP CHAR(5),
	TENSP NVARCHAR(50),
	GIA FLOAT(5) CHECK (GIA>=0),
	MADT CHAR(5),
	CHINHANH NVARCHAR(50),
	PRIMARY KEY(MASP)
)
CREATE TABLE KHACHHANG(
	MAKH CHAR(5),
	HOTEN NVARCHAR(10),
	SODT VARCHAR(20),
	DCHI NVARCHAR(50),
	EMAIL VARCHAR(20),
	PRIMARY KEY(MAKH)
)
CREATE TABLE TAIXE(
	MANV CHAR(5),
	HOTEN NVARCHAR(10),
	CMND VARCHAR(20),
	SODT VARCHAR(20),
	DCHI NVARCHAR(50),
	BIENXE VARCHAR(20),
	KHUVUC NVARCHAR(50),
	EMAIL VARCHAR(20),
	STK VARCHAR(20),
	PRIMARY KEY(MANV)
)
CREATE TABLE DONHANG(
	MADH CHAR(5),
	KHACHHANG CHAR(5),
	SANPHAM CHAR(5),
	SOLUONG INT CHECK (SOLUONG>0),
	HINHTHUCTT NVARCHAR(50) CHECK (HINHTHUCTT=N'TIỀN MẶT' OR HINHTHUCTT=N'CHUYỂN KHOẢN'),
	DCHIGIAO NVARCHAR(50),
	PHISANPHAM FLOAT(10) CHECK (PHISANPHAM>0),
	PHIVANCHUYEN FLOAT(10) CHECK (PHIVANCHUYEN>=0),
	TINHTRANG NVARCHAR(30) CHECK (TINHTRANG=N'ĐÃ ĐẶT' OR TINHTRANG=N'ĐANG VẬN CHUYỂN' OR TINHTRANG=N'ĐÃ GIAO' OR TINHTRANG=N'ĐÃ HỦY'),
	NGUOIGIAO CHAR(5),
	PRIMARY KEY(MADH)
)
CREATE TABLE TAIKHOAN(
	TAIKHOAN VARCHAR(20),
	MATKHAU VARCHAR(20),
	MANGUOIDUNG CHAR(5),
	VAITRO VARCHAR(10) CHECK (VAITRO='client' OR VAITRO='customer' OR VAITRO='driver' OR VAITRO='admin' OR VAITRO='staff'),
	KICHHOAT INT CHECK(KICHHOAT=1 OR KICHHOAT=0),
	PRIMARY KEY(TAIKHOAN)
)
GO
ALTER TABLE CHINHANH
	ADD CONSTRAINT FK_CHINHANH_MADT
	FOREIGN KEY(MADT)
	REFERENCES DOITAC(MADT)
GO
ALTER TABLE CHINHANHDKY
	ADD CONSTRAINT FK_CNDK_MADTDCHI
	FOREIGN KEY(MADT, DCHI) 
	REFERENCES CHINHANH(MADT, DCHI)
GO
ALTER TABLE CHINHANHDKY
	ADD CONSTRAINT FK_CNDK_MAHD
	FOREIGN KEY(MAHD) 
	REFERENCES HOPDONG(MAHD)
GO 
ALTER TABLE SANPHAM
	ADD CONSTRAINT FK_SANPHAM_MADTCHINHANH
	FOREIGN KEY(MADT, CHINHANH) 
	REFERENCES CHINHANH(MADT, DCHI)
GO
ALTER TABLE DONHANG
	ADD CONSTRAINT FK_DONHANG_NGUOIGIAO
	FOREIGN KEY(NGUOIGIAO) 
	REFERENCES TAIXE(MANV)
GO
ALTER TABLE DONHANG
	ADD CONSTRAINT FK_DONHANG_KHACHHANG
	FOREIGN KEY(KHACHHANG) 
	REFERENCES KHACHHANG(MAKH)
GO 
ALTER TABLE DONHANG
	ADD CONSTRAINT FK_DONHANG_SANPHAM
	FOREIGN KEY(SANPHAM) 
	REFERENCES SANPHAM(MASP)