USE DB_QUANLYDATHANG
GO
CREATE LOGIN TESTDT WITH PASSWORD = '1234'
CREATE LOGIN TESTKH WITH PASSWORD = '1234'
CREATE LOGIN TESTTX WITH PASSWORD = '1234'
CREATE LOGIN TESTNV WITH PASSWORD = '1234'
CREATE LOGIN TESTAD WITH PASSWORD = '1234'

CREATE USER DT1 FOR LOGIN TESTDT
CREATE USER KH1 FOR LOGIN TESTKH
CREATE USER TX1 FOR LOGIN TESTTX
CREATE USER NV1 FOR LOGIN TESTNV
CREATE USER AD1 FOR LOGIN TESTAD

CREATE ROLE DB_CLIENT 
CREATE ROLE DB_CUSTOMER
CREATE ROLE DB_DRIVER
CREATE ROLE DB_STAFF
CREATE ROLE DB_ADMIN

GO
GRANT INSERT ON SANPHAM TO DB_CLIENT
GO
CREATE VIEW DOITACSANPHAM AS
SELECT SP.*
FROM TAIKHOAN TK JOIN DOITAC DT ON TK.MANGUOIDUNG = DT.MADT JOIN SANPHAM SP ON DT.MADT = SP.MADT
WHERE TK.TAIKHOAN = CURRENT_USER
GO
GRANT SELECT, UPDATE, DELETE ON DOITACSANPHAM TO DB_CLIENT
GO
CREATE VIEW DOITACDONHANG AS
SELECT DH.*
FROM DONHANG DH JOIN SANPHAM SP ON DH.SANPHAM = SP.MASP JOIN DOITAC DT ON SP.MADT = DT.MADT JOIN TAIKHOAN TK ON TK.MANGUOIDUNG = DT.MADT
WHERE TK.TAIKHOAN = CURRENT_USER
GO
GRANT SELECT ON DOITACDONHANG TO DB_CLIENT
GRANT UPDATE ON DOITACDONHANG(TINHTRANG) TO DB_CLIENT
GO
CREATE VIEW THONGTINDOITAC AS
SELECT DT.*
FROM TAIKHOAN TK JOIN DOITAC DT ON TK.MANGUOIDUNG = DT.MADT
WHERE TK.TAIKHOAN = CURRENT_USER
GO
GRANT SELECT, UPDATE ON THONGTINDOITAC TO DB_CLIENT
GO
CREATE VIEW DOITACCHINHANH AS
SELECT CN.*
FROM CHINHANH CN JOIN DOITAC DT ON CN.MADT = DT.MADT JOIN TAIKHOAN TK ON TK.MANGUOIDUNG = DT.MADT
WHERE TK.TAIKHOAN = CURRENT_USER
GO
GRANT INSERT ON CHINHANH TO DB_CLIENT
GRANT SELECT, UPDATE, DELETE ON DOITACCHINHANH TO DB_CLIENT

GO
CREATE VIEW THONGTINKHACHHANG AS
SELECT KH.*
FROM TAIKHOAN TK JOIN KHACHHANG KH ON TK.MANGUOIDUNG = KH.MAKH
WHERE TK.TAIKHOAN = CURRENT_USER
GO
GRANT SELECT, UPDATE ON THONGTINKHACHHANG TO DB_CUSTOMER
GRANT SELECT ON DOITAC TO DB_CUSTOMER
GO
CREATE VIEW KHACHHANGDONHANG AS
SELECT DH.*
FROM TAIKHOAN TK JOIN KHACHHANG KH ON TK.MANGUOIDUNG = KH.MAKH JOIN DONHANG DH ON KH.MAKH = DH.KHACHHANG
WHERE TK.TAIKHOAN = CURRENT_USER
GO
GRANT SELECT, DELETE ON KHACHHANGDONHANG TO DB_CUSTOMER
GRANT INSERT ON DONHANG TO DB_CUSTOMER

GO
CREATE VIEW THONGTINTAIXE AS
SELECT TX.*
FROM TAIKHOAN TK JOIN TAIXE TX ON TK.MANGUOIDUNG = TX.MANV
WHERE TK.TAIKHOAN = CURRENT_USER
GO
GRANT SELECT, UPDATE ON THONGTINTAIXE TO DB_DRIVER
GO
CREATE VIEW DONHANGDANHAN AS
SELECT DH.*
FROM TAIKHOAN TK JOIN TAIXE TX ON TK.MANGUOIDUNG = TX.MANV JOIN DONHANG DH ON TX.MANV = DH.NGUOIGIAO
WHERE TK.TAIKHOAN = CURRENT_USER
GO
GRANT SELECT ON DONHANGDANHAN TO DB_DRIVER
GRANT UPDATE ON DONHANGDANHAN(TINHTRANG) TO DB_DRIVER
GO
CREATE VIEW DONHANGCOTHENHAN AS
SELECT DH.*
FROM DONHANG DH
WHERE DH.NGUOIGIAO IS NULL AND DH.DCHIGIAO LIKE '%' + (SELECT TX.KHUVUC FROM TAIKHOAN TK JOIN TAIXE TX ON TK.MANGUOIDUNG = TX.MANV WHERE TK.TAIKHOAN = CURRENT_USER)
GO
GRANT SELECT ON DONHANGCOTHENHAN TO DB_DRIVER
GRANT UPDATE ON DONHANGCOTHENHAN(NGUOIGIAO) TO DB_DRIVER

GRANT SELECT ON HOPDONG TO DB_STAFF
GRANT UPDATE ON HOPDONG(HIEULUC) TO DB_STAFF

GRANT ALL ON TAIKHOAN TO DB_ADMIN
GRANT SELECT, UPDATE ON DOITAC TO DB_ADMIN
GRANT SELECT, UPDATE ON KHACHHANG TO DB_ADMIN
GRANT SELECT, UPDATE ON TAIXE TO DB_ADMIN

GO
ALTER ROLE DB_CLIENT ADD MEMBER DT1
ALTER ROLE DB_CUSTOMER ADD MEMBER KH1
ALTER ROLE DB_DRIVER ADD MEMBER TX1
ALTER ROLE DB_STAFF ADD MEMBER NV1
ALTER ROLE DB_ADMIN ADD MEMBER AD1