--CREATE
ALTER
PROC KH_HUYDONHANG
	@MAKH CHAR(5),
	@MADH CHAR(5)
AS
BEGIN TRAN
SET TRAN ISOLATION LEVEL REPEATABLE READ
		IF NOT EXISTS(SELECT * FROM DONHANG DH WHERE DH.MADH=@MADH)
		BEGIN
			PRINT @MADH + N' KHÔNG TỒN TẠI'
			ROLLBACK TRAN
			RETURN 0
		END
		IF NOT EXISTS(SELECT * FROM DONHANG DH WHERE DH.MADH=@MADH AND DH.KHACHHANG=@MAKH)
		BEGIN
			PRINT @MADH + N' KHÔNG THUỘC VỀ ' + @MAKH
			ROLLBACK TRAN
			RETURN 0
		END
		UPDATE DOITAC
		SET SLDON = SLDON - 1
		WHERE MADT = (SELECT SP.MADT FROM DONHANG DH JOIN SANPHAM SP ON DH.SANPHAM = SP.MASP WHERE DH.MADH=@MADH)
		WAITFOR DELAY '0:0:10'
		DELETE DONHANG
		WHERE MADH = @MADH
COMMIT TRAN
RETURN 1
GO

--CREATE
ALTER 
PROC DT_CAPNHATDONHANG
	@MADT CHAR(5),
	@MADH CHAR(5),
	@TINHTRANG NVARCHAR(30)
AS
BEGIN TRAN
SET TRAN ISOLATION LEVEL REPEATABLE READ
		IF NOT EXISTS(SELECT * FROM DONHANG DH WHERE DH.MADH=@MADH)
		BEGIN
			PRINT @MADH + N' KHÔNG TỒN TẠI'
			ROLLBACK TRAN
			RETURN 0
		END
		IF NOT EXISTS(SELECT * FROM DONHANG DH JOIN SANPHAM SP ON DH.SANPHAM=SP.MASP WHERE DH.MADH=@MADH AND SP.MADT=@MADT)
		BEGIN
			PRINT @MADH + N' KHÔNG THUỘC VỀ ' + @MADT
			ROLLBACK TRAN
			RETURN 0
		END
		IF @TINHTRANG NOT IN(N'ĐÃ HỦY', N'ĐANG VẬN CHUYỂN')
		BEGIN
			PRINT @TINHTRANG + N' KHÔNG HỢP LỆ'
			ROLLBACK TRAN
			RETURN 0
		END
		IF @TINHTRANG = N'ĐÃ HỦY'
		BEGIN
			DELETE DONHANG
			WHERE MADH = @MADH
			WAITFOR DELAY '0:0:10'
			UPDATE DOITAC
			SET SLDON = SLDON - 1
			WHERE MADT = (SELECT SP.MADT FROM DONHANG DH JOIN SANPHAM SP ON DH.SANPHAM = SP.MASP WHERE DH.MADH=@MADH)
		END
		ELSE
		BEGIN
			UPDATE DONHANG
			SET TINHTRANG = @TINHTRANG
			WHERE MADH = @MADH
		END
COMMIT TRAN
RETURN 1
GO